### ISSUE TITLE
v4.0.0-pre : error when load blend file

### ISSUE THREAD

**Issue by listelin** [UuuNyaa/blender_mmd_uuunyaa_tools#123]
blender 4.1.1
MMD Tools v4.0.0 pre-release

when load blend file, the following error appears in the console log
I don't see any other problems, only logs.
```
Read blend: "E:\dev\myblend\mmd41import-test.blend"
Error in bpy.app.handlers.load_post[7]:
Traceback (most recent call last):
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\handlers.py", line 21, in load_hander
    MigrationFnMaterial.update_mmd_shader()
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\core\material.py", line 682, in update_mmd_shader
    if "Color" in mmd_shader_node_tree.outputs:
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ShaderNodeTree' object has no attribute 'outputs'
```

**Comment by listelin** [comment]
not blender_mmd_uuunyaa_tools,  blender_mmd_tools's issue
