### ISSUE TITLE
v4.0.0-pre: can't bake (by mmd panel bake button)

### ISSUE THREAD

**Issue by listelin** [UuuNyaa/blender_mmd_uuunyaa_tools#124]
blender-4.1.1
mmd tools [v4.0.0](https://github.com/UuuNyaa/blender_mmd_tools/releases/tag/v4.0.0)

When I press the bake button on **MMD panel**, the following error message appears in the console and I cannot bake.

**Rigid body world > cache > bake works fine.**

```
Traceback (most recent call last):
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\operators\rigid_body.py", line 309, in execute
    bpy.ops.ptcache.bake(override, "INVOKE_DEFAULT", bake=True)
  File "C:\blender\blender-4.1.1-stable+v41.e1743a0317bc-windows.amd64-release\4.1\scripts\modules\bpy\ops.py", line 106, in __call__
    C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\blender\blender-4.1.1-stable+v41.e1743a0317bc-windows.amd64-release\4.1\scripts\modules\bpy\ops.py", line 60, in _parse_args
    raise ValueError("1-2 args execution context is supported")
ValueError: 1-2 args execution context is supported
Error: Python: Traceback (most recent call last):
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\operators\rigid_body.py", line 309, in execute
    bpy.ops.ptcache.bake(override, "INVOKE_DEFAULT", bake=True)
  File "C:\blender\blender-4.1.1-stable+v41.e1743a0317bc-windows.amd64-release\4.1\scripts\modules\bpy\ops.py", line 106, in __call__
    C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\blender\blender-4.1.1-stable+v41.e1743a0317bc-windows.amd64-release\4.1\scripts\modules\bpy\ops.py", line 60, in _parse_args
    raise ValueError("1-2 args execution context is supported")
ValueError: 1-2 args execution context is supported
```

**Comment by listelin** [comment]
not blender_mmd_uuunyaa_tools,  blender_mmd_tools's issue
