### ISSUE TITLE
Fail to convert rigify to MMD compatibale

### ISSUE THREAD

**Issue by NaughtDZ** [UuuNyaa/blender_mmd_uuunyaa_tools#127]
Traceback (most recent call last):
  File "C:\Users\Naught\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\mmd_uuunyaa_tools\converters\armatures\operators.py", line 368, in execute
    rigify_armature_object.imitate_mmd_bone_structure()
  File "C:\Users\Naught\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\mmd_uuunyaa_tools\converters\armatures\rigify.py", line 542, in imitate_mmd_bone_structure
    center_bone, groove_bone = self._add_root_bones(rig_edit_bones)
  File "C:\Users\Naught\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\mmd_uuunyaa_tools\converters\armatures\rigify.py", line 446, in _add_root_bones
    thigh_center = self.to_center(rig_edit_bones['ORG-thigh.L'].head, rig_edit_bones['ORG-thigh.L'].head)
KeyError: 'bpy_prop_collection[key]: key "ORG-thigh.L" not found'
閿欒: Python: Traceback (most recent call last):
  File "C:\Users\Naught\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\mmd_uuunyaa_tools\converters\armatures\operators.py", line 368, in execute
    rigify_armature_object.imitate_mmd_bone_structure()
  File "C:\Users\Naught\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\mmd_uuunyaa_tools\converters\armatures\rigify.py", line 542, in imitate_mmd_bone_structure
    center_bone, groove_bone = self._add_root_bones(rig_edit_bones)
  File "C:\Users\Naught\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\mmd_uuunyaa_tools\converters\armatures\rigify.py", line 446, in _add_root_bones
    thigh_center = self.to_center(rig_edit_bones['ORG-thigh.L'].head, rig_edit_bones['ORG-thigh.L'].head)
KeyError: 'bpy_prop_collection[key]: key "ORG-thigh.L" not found'

What should I do?

**Comment by ulyssas** [comment]
Without access to the model that causes this problem, I cannot really help you.
I think you used Rigify to MMD feature, which requires Rigify Humanoid to be there. If it's not, then you can't convert.
The error `KeyError: 'bpy_prop_collection[key]: key "ORG-thigh.L" not found'` means it's missing thigh bone.
