### ISSUE TITLE
MMD UuuNyaa Tools's MMD Rigify Integration feature Error

### ISSUE THREAD

**Issue by Be3up** [UuuNyaa/blender_mmd_uuunyaa_tools#138]
Python: Traceback (most recent call last):
  File "C:\Users\Vezir\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\mmd_uuunyaa_tools\converters\armatures\operators.py", line 33, in poll
    return MMDArmatureObject.is_mmd_armature_object(context.active_object)
  File "C:\Users\Vezir\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\mmd_uuunyaa_tools\converters\armatures\mmd.py", line 162, in is_mmd_armature_object
    if import_mmd_tools().core.model.Model.findRoot(obj) is None:
  File "C:\Users\Vezir\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\mmd_tools\core\model.py", line 363, in findRoot
    return FnModel.find_root(obj)
  File "C:\Users\Vezir\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\mmd_tools\core\model.py", line 99, in find_root
    if obj.mmd_type == 'ROOT':
AttributeError: 'Object' object has no attribute 'mmd_type'. Did you mean: 'rna_type'?

**Comment by ulyssas** [comment]
If you are still using Blender 3.5, install MMD Tools v2.10.3 & UuuNyaa Tools v1.8.0 and see if that fixes. If it doesn't, tell me what model causes the issue.
