### ISSUE TITLE
uuunyaa_tools error in blender 2.93

### ISSUE THREAD

**Issue by listelin** [UuuNyaa/blender_mmd_uuunyaa_tools#30]
まだベータバージョンですが、Blender 2.93で動作確認したところ、0.6.1以降でエラーが発生しました

1. 前提として、Blender 2.93では、mmd_toolsを2021/5/22以降のバージョンに更新する必要があります
As a prerequisite, for Blender 2.93, mmd_tools needs to be updated to a version after 5/22/2021
https://github.com/powroupi/blender_mmd_tools/archive/dev_test.zip

2. uuunyaa_tools 0.6.0はBlender 2.93で問題なく動作しますが、0.6.1 - 0.6.4では起動時に以下のエラーが発生します。
uuunyaa_tools 0.6.0 works fine with Blender 2.93, but with 0.6.1 - 0.6.4, I get the following error at startup

対応は正式版リリース後(2021/6/2予定）で良いと思いますが気が付きましたのでご報告まで。
正式版リリース後に確認してまた追記します。
I think it should be supported after the official release (scheduled for June 2, 2021), but I've noticed it, so I'll report it.
I'll check it after the official release and add it again.

```
Traceback (most recent call last):
  File "C:\blender\blender-2.93.0-beta+blender-v293-release.ba4228bcf77e-windows.amd64-release\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\__init__.py", line 43, in <module>
    auto_load.init()
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\auto_load.py", line 26, in init
    ordered_classes = get_ordered_classes_to_register(modules)
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\auto_load.py", line 73, in get_ordered_classes_to_register
    return toposort(get_register_deps_dict(modules))
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\auto_load.py", line 81, in get_register_deps_dict
    deps_dict[cls] = set(iter_my_register_deps(cls, my_classes, my_classes_by_idname))
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\auto_load.py", line 85, in iter_my_register_deps
    yield from iter_my_deps_from_annotations(cls, my_classes)
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\auto_load.py", line 89, in iter_my_deps_from_annotations
    for value in typing.get_type_hints(cls, {}, {}).values():
  File "C:\blender\blender-2.93.0-beta+blender-v293-release.ba4228bcf77e-windows.amd64-release\2.93\python\lib\typing.py", line 1417, in get_type_hints
    value = _eval_type(value, base_globals, localns)
  File "C:\blender\blender-2.93.0-beta+blender-v293-release.ba4228bcf77e-windows.amd64-release\2.93\python\lib\typing.py", line 283, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\blender\blender-2.93.0-beta+blender-v293-release.ba4228bcf77e-windows.amd64-release\2.93\python\lib\typing.py", line 539, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'EnumProperty' is not defined
```

確認バージョン
 5/30 03:24:06 blender-2.93.0-beta+blender-v293-release.3c02e648f395-windows.amd64-release

*Blender 2.92では問題ありません
No problem with Blender 2.92

**Comment by UuuNyaa** [comment]
確認ありがとうございます。
自動ローダー部分は JacquesLucke/blender_vscode に依存しているので、そちらの対応を待ってみます。

Thanks for the checking.
The auto loader part is dependent on JacquesLucke/blender_vscode , so I'll wait for that to be addressed for the time being.

https://github.com/JacquesLucke/blender_vscode/blob/master/pythonFiles/templates/addons/with_auto_load/auto_load.py

**Comment by listelin** [comment]
Blender 2.9.3 / Windows 10
2点問題があります。

1. 起動時エラー
 JacquesLucke/blender_vscodeの問題なのでしょうが、暫定対応として、editors/skin_hair.py を削除することで解決します。
```
Traceback (most recent call last):
  File "C:\blender\blender-2.93.0-windows64\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\__init__.py", line 43, in <module>
    auto_load.init()
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\auto_load.py", line 26, in init
    ordered_classes = get_ordered_classes_to_register(modules)
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\auto_load.py", line 73, in get_ordered_classes_to_register
    return toposort(get_register_deps_dict(modules))
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\auto_load.py", line 81, in get_register_deps_dict
    deps_dict[cls] = set(iter_my_register_deps(cls, my_classes, my_classes_by_idname))
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\auto_load.py", line 85, in iter_my_register_deps
    yield from iter_my_deps_from_annotations(cls, my_classes)
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\auto_load.py", line 89, in iter_my_deps_from_annotations
    for value in typing.get_type_hints(cls, {}, {}).values():
  File "C:\blender\blender-2.93.0-windows64\2.93\python\lib\typing.py", line 1417, in get_type_hints
    value = _eval_type(value, base_globals, localns)
  File "C:\blender\blender-2.93.0-windows64\2.93\python\lib\typing.py", line 283, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\blender\blender-2.93.0-windows64\2.93\python\lib\typing.py", line 539, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'EnumProperty' is not defined
```

2. AssetSearch Import / Download 時にエラーが発生する
```
ContentCache.__init__: cache_folder=C:\Users\a\AppData\Local\Temp\mmd_uuunyaa_tools_cache, temporary_dir=C:\Users\a\AppData\Local\Temp\tmpuf8vank0
_load_contents: 114 from C:\Users\a\AppData\Local\Temp\mmd_uuunyaa_tools_cache\contents.json
do: MMD_UUUNYAA_TOOLS_OT_asset_import
Python: Traceback (most recent call last):
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\asset_search\panels.py", line 219, in execute
    ImportActionExecutor.execute_import_action(asset, content.filepath if content is not None else None)
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\asset_search\actions.py", line 390, in execute_import_action
    RestrictionChecker(*(functions.keys())).visit(tree)
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\asset_search\actions.py", line 39, in visit
    return self.generic_visit(node)
  File "C:\blender\blender-2.93.0-windows64\2.93\python\lib\ast.py", line 415, in generic_visit
    self.visit(item)
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\asset_search\actions.py", line 39, in visit
    return self.generic_visit(node)
  File "C:\blender\blender-2.93.0-windows64\2.93\python\lib\ast.py", line 417, in generic_visit
    self.visit(value)
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\asset_search\actions.py", line 39, in visit
    return self.generic_visit(node)
  File "C:\blender\blender-2.93.0-windows64\2.93\python\lib\ast.py", line 415, in generic_visit
    self.visit(item)
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\asset_search\actions.py", line 33, in visit
    raise NotImplementedError(ast.dump(node))
NotImplementedError: Constant(value='芭芭拉/芭芭拉.pmx')
```

asset_search/actions.py Line 33を修正することでエラーは解消します。
```
    def visit(self, node: ast.AST):
        node_name = node.__class__.__name__

-        if node_name not in {'Module', 'Expr', 'Call', 'Name', 'Str', 'JoinedStr', 'FormattedValue', 'Load', 'Num', 'keyword'}:
+        if node_name not in {'Module', 'Expr', 'Call', 'Name', 'Str', 'JoinedStr', 'FormattedValue', 'Load', 'Num', 'keyword','Constant'}:
            raise NotImplementedError(ast.dump(node))
```

node.__class__.__name__　の結果が変わったようです。
| 2.92 | 2.93 | |
|--|--|--|
| Module | Module| | |
| Expr | Expr | |
| Call | Call  | |
| Name | Name | |
| Load| Load | |
| Keyword | Keyword  | |
| Str | Constant  | Error |
| Num | Constant  | Error |

---
1. v2.9.3 Error on startup
 This is probably a problem with JacquesLucke/blender_vscode, but as a temporary fix, you can remove editors/skin_hair.py.

2. An error occurs during AssetSearch Import / Download
The error can be fixed by modifying asset_search/actions.py Line 33.
```
    def visit(self, node: ast.AST):
        node_name = node.__class__.__name__

-        if node_name not in {'Module', 'Expr', 'Call', 'Name', 'Str', 'JoinedStr', 'FormattedValue', 'Load', 'Num', 'keyword'}:
+        if node_name not in {'Module', 'Expr', 'Call', 'Name', 'Str', 'JoinedStr', 'FormattedValue', 'Load', 'Num', 'keyword','Constant'}:
            raise NotImplementedError(ast.dump(node))
```

**Comment by listelin** [comment]
2.9.3でも以下の機能は正常に動作しているようです（詳細な確認はしていませんがエラーは出ません）
The following functions seem to work fine in 2.9.3 (I haven't checked in detail, but no errors appear)

Rigify Integration：OK
Setup Rnder Engine for Eevee : OK
Uuunyaa Lighting: OK
Uuunyaa materials: OK
Conver Shader for Eevee: OK

**Comment by UuuNyaa** [comment]
調査ありがとうございます。
2.93からPythonインタプリタのバージョンが変わっているようですね。

Thank you for your research.
It seems that the Python interpreter version has changed since 2.93.

https://wiki.blender.org/wiki/Reference/Release_Notes/2.93/Python_API

**Comment by UuuNyaa** [comment]
Blender 2.93 LTS が正式公開されたので、優先度を上げます。

Now that Blender 2.93 LTS has been officially released, I'm going to prioritize this issue.

https://www.blender.org/download/releases/2-93/

**Comment by UuuNyaa** [comment]
This issue has been fixed in v0.7.0
