### ISSUE TITLE
It can not active addon

### ISSUE THREAD

**Issue by rlsl0422** [UuuNyaa/blender_mmd_uuunyaa_tools#55]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\PC\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\gscatter\libmanager\t3dn.py", line 595, in _packer_import
    return _orig_import(name, globals, locals, fromlist, level)
  File "C:\Users\PC\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\__init__.py", line 60, in <module>
    auto_load.init()
  File "C:\Users\PC\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\auto_load.py", line 25, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "C:\Users\PC\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\auto_load.py", line 53, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "C:\Users\PC\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\auto_load.py", line 57, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\PC\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\converters\physics\cloth.py", line 15, in <module>
    mmd_tools = import_mmd_tools()
  File "C:\Users\PC\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\utilities.py", line 72, in import_mmd_tools
    return importlib.import_module('mmd_tools')
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmd_tools'

**Comment by UuuNyaa** [comment]
If the error is reported when you try to use mmd_uuunyaa_tools features, you probably have not pre-installed mmd_tools.
To fix this, follow the How to install MMD UuuNyaa Tools  exactly to install.
In particular, you meet the Requirements.
https://github.com/UuuNyaa/blender_mmd_uuunyaa_tools/wiki#requirements

**Comment by UuuNyaa** [comment]
Same as #51

**Comment by UuuNyaa** [comment]
Since the same problem is often reported, I wrote an article: [Why can't I use MMD UuuNyaa Tools?](https://mmd-blender.fandom.com/wiki/Why_can%27t_I_use_MMD_UuuNyaa_Tools%3F)
