### ISSUE TITLE
Add on wont install on Blender 2.93 or 2.92

### ISSUE THREAD

**Issue by CrossPadGaming** [UuuNyaa/blender_mmd_uuunyaa_tools#64]
This is the message I get when I try to install the Add on, I even downloaded  the new version of Blender to install this.

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\leacr\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\__init__.py", line 60, in <module>
    auto_load.init()
  File "C:\Users\leacr\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\auto_load.py", line 25, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "C:\Users\leacr\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\auto_load.py", line 53, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "C:\Users\leacr\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\auto_load.py", line 57, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\leacr\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\converters\physics\cloth.py", line 15, in <module>
    mmd_tools = import_mmd_tools()
  File "C:\Users\leacr\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\utilities.py", line 72, in import_mmd_tools
    return importlib.import_module('mmd_tools')
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmd_tools'

**Comment by CrossPadGaming** [comment]
anything I can do?

**Comment by CrossPadGaming** [comment]
I installed it but I got that warning when I tried to enable it.

**Comment by UuuNyaa** [comment]
It's probably the same problem as the following issues:
* #51 
* #55

**Comment by CrossPadGaming** [comment]
thank you!
