### ISSUE TITLE
cannot activate v1.5.0 on a fresh version of blender 3.3

### ISSUE THREAD

**Issue by LauraKami** [UuuNyaa/blender_mmd_uuunyaa_tools#86]
****** first try ******
First try, install the zip from github 'mmd_uuunyaa_tools-v1.5.0.zip on a new blender 3.3 LTS installation.
it bug on "No module named 'mmd_tools'"

Modules Installed (mmd_uuunyaa_tools) from 'C:\\SOFTS\\Blender\\mmd_tools\\mmd_uuunyaa_tools-v1.5.0.zip' into 'C:\\Users\\blender\\AppData\\Roaming\\Blender Foundation\\Blender\\3.2\\scripts\\addons'
Traceback (most recent call last):
  File "C:\SOFTS\Blender\3.2\3.2\scripts\modules\addon_utils.py", line 335, in enable
    mod = __import__(module_name)
  File "C:\Users\blender\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\mmd_uuunyaa_tools\__init__.py", line 60, in <module>
    auto_load.init()
  File "C:\Users\blender\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\mmd_uuunyaa_tools\auto_load.py", line 25, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "C:\Users\blender\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\mmd_uuunyaa_tools\auto_load.py", line 53, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "C:\Users\blender\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\mmd_uuunyaa_tools\auto_load.py", line 57, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "C:\SOFTS\Blender\3.2\3.2\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\blender\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\mmd_uuunyaa_tools\converters\physics\cloth.py", line 15, in <module>
    mmd_tools = import_mmd_tools()
  File "C:\Users\blender\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\mmd_uuunyaa_tools\utilities.py", line 72, in import_mmd_tools
    return importlib.import_module('mmd_tools')
  File "C:\SOFTS\Blender\3.2\3.2\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmd_tools'

************ how to solve the problem (  ) *******
Install the "blender_mmd_tools" first
(https://github.com/UuuNyaa/blender_mmd_tools)
close blender, restart blender
activate "blender_mmd_tools"
install "mmd_uuunyaa_tools", 
After you can activate the mmd_uuunyaa_tools   v 1.5.0. it work fine ;o)

Sorry for this bad globish

Thank you in any case for maintaining and enriching this addOn.
Laura

**Comment by UuuNyaa** [comment]
Thank you for the report 😃

The problem is that the names `mmd_tools` and `mmd_uuunyaa_tools` are too similar.
We can't change the name now, so we need to make the document easier to understand.

**Comment by LauraKami** [comment]
Thank you for your reply
suggestion, modify the first page as follows :
_just after_ 
mmd_uuunyaa_tools is a blender addon for adjust scenes, models and materials in concert with [UuuNyaa/blender_mmd_tools](https://github.com/UuuNyaa/blender_mmd_tools).
_add this 2 lines :_
1) First step : Install **blender_mmd_tools**   (https://github.com/UuuNyaa/blender_mmd_tools)
2) Second step : Install this tool **mmd_uuunyaa_tools** (you are here ;o)

just 2 lines, for remove some tickets and (new ) user frustration. (yep newbe like me)
Have a good day.
