### ISSUE TITLE
asset serach import error

### ISSUE THREAD

**Issue by listelin** [UuuNyaa/blender_mmd_uuunyaa_tools#9]
#8 を解消後、検索及びダウンロードは正常にできましたが、Importで以下のエラーとなります。

ContentCache.__init__: cache_folder=C: \Users\xxx\AppData\Local\Temp\mmd_uuunyaa_tools_cache, temporary_dir=C: \Users\xxx\AppData\Local\Temp\tmpxlphw3ht
_load_contents: 2 from C: \Users\xxx\AppData\Local\Temp\mmd_uuunyaa_tools_cache\contents.json
do: MMD_UUUNYAA_TOOLS_OT_asset_import
unrar(C: \Users\xxx\AppData\Local\Temp\mmd_uuunyaa_tools_cache\e6b2e070,C:\Users\a\BlenderAssets\MODEL_MMD/00005.Lisa,C:\Users\a\BlenderAssets\MODEL_MMD/00005.Lisa\00005.json)
Python: Traceback (most recent call last):
  File "C: \Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\asset_search\panels.py", line 201, in execute
    ASSETS.execute_import_action(asset.id, content.filepath if content is not None else None)
  File "C: \Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\asset_search\assets.py", line 302, in execute_import_action
    _Utilities.execute_import_action(self[id], target_file)
  File "C: \Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\asset_search\assets.py", line 258, in execute_import_action
    'file': target_file,
  File "<source>", line 1, in <module>
  File "C: \Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\asset_search\assets.py", line 99, in unrar
    rar.extractall(path=asset_path, pwd=password)
  File "C: \Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\externals\rarfile\rarfile.py", line 847, in extractall
    dst = self._extract_one(inf, path, pwd, not inf.is_dir())
  File "C: \Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\externals\rarfile\rarfile.py", line 912, in _extract_one
    return self._make_file(info, dstfn, pwd, set_attrs)
  File "C: \Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\externals\rarfile\rarfile.py", line 925, in _make_file
    with self.open(info, "r", pwd) as src:
  File "C: \Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\externals\rarfile\rarfile.py", line 783, in open
    return self._file_parser.open(inf, pwd)
  File "C: \Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\externals\rarfile\rarfile.py", line 1237, in open
    return self._open_hack(inf, pwd)
  File "C: \Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\externals\rarfile\rarfile.py", line 2073, in _open_hack
    return self._open_hack_core(inf, pwd, RAR5_ID + main_hdr, endarc_hdr)
  File "C: \Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\externals\rarfile\rarfile.py", line 1275, in _open_hack_core
    return self._open_unrar(tmpname, inf, pwd, tmpname)
  File "C: \Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\externals\rarfile\rarfile.py", line 1286, in _open_unrar
    setup = tool_setup()
  File "C: \Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\externals\rarfile\rarfile.py", line 3335, in tool_setup
    raise RarCannotExec("Cannot find working tool")
rarfile.RarCannotExec: Cannot find working tool

location: <unknown location>:-1
繧ｨ繝ｩ繝ｼ: Python: Traceback (most recent call last):
  File "C: \Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\asset_search\panels.py", line 201, in execute
    ASSETS.execute_import_action(asset.id, content.filepath if content is not None else None)
  File "C: \Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\asset_search\assets.py", line 302, in execute_import_action
    _Utilities.execute_import_action(self[id], target_file)
  File "C: \Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\asset_search\assets.py", line 258, in execute_import_action
    'file': target_file,
  File "<source>", line 1, in <module>
  File "C: \Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\asset_search\assets.py", line 99, in unrar
    rar.extractall(path=asset_path, pwd=password)
  File "C: \Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\externals\rarfile\rarfile.py", line 847, in extractall
    dst = self._extract_one(inf, path, pwd, not inf.is_dir())
  File "C: \Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\externals\rarfile\rarfile.py", line 912, in _extract_one
    return self._make_file(info, dstfn, pwd, set_attrs)
  File "C: \Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\externals\rarfile\rarfile.py", line 925, in _make_file
    with self.open(info, "r", pwd) as src:
  File "C: \Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\externals\rarfile\rarfile.py", line 783, in open
    return self._file_parser.open(inf, pwd)
  File "C: \Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\externals\rarfile\rarfile.py", line 1237, in open
    return self._open_hack(inf, pwd)
  File "C: \Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\externals\rarfile\rarfile.py", line 2073, in _open_hack
    return self._open_hack_core(inf, pwd, RAR5_ID + main_hdr, endarc_hdr)
  File "C: \Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\externals\rarfile\rarfile.py", line 1275, in _open_hack_core
    return self._open_unrar(tmpname, inf, pwd, tmpname)
  File "C: \Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\externals\rarfile\rarfile.py", line 1286, in _open_unrar
    setup = tool_setup()
  File "C: \Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\externals\rarfile\rarfile.py", line 3335, in tool_setup
    raise RarCannotExec("Cannot find working tool")
rarfile.RarCannotExec: Cannot find working tool

location: <unknown location>:-1

**Comment by listelin** [comment]
以下２点により動作するようになりました。　素晴らしい！
(1)WinRARをダウンロードしインストール
https://www.rarlab.com/download.htm

(2)WindowsのPATHにC:\Program Files\WinRARを追加

参考　https://github.com/markokr/rarfile/issues/61

**Comment by UuuNyaa** [comment]
Windows環境でのテストありがとうございます。
同じ問題が起きたときに、コメントしてくれた手順を表示するようにします。

Thank you for testing on a Windows environment.
I'll show the steps you commented on when the same problem occurs.

**Comment by UuuNyaa** [comment]
エラー発生時にダイアログ表示する方法がわかりません。
ダイアログ表示をあきらめて、インストール手順wikiを整備して解決しようと思います。

I don't know how to display a dialog when the error occurs.
I'll give up on the dialog display and write installation instruction wiki to solve the issue.

**Comment by listelin** [comment]
Ubuntu 10.04のデフォルトインストールでも同じ事象になったので報告します

sudo apt-get install unrar　でunrarをインストールすればいいだけですが

**Comment by UuuNyaa** [comment]
![image](https://user-images.githubusercontent.com/70152495/109827232-e682fe00-7c7e-11eb-9e23-30d668c6eff9.png)
ダイアログの表示ができました。
I was able to display the dialog.

**Comment by UuuNyaa** [comment]
導入方法を書きました。
I wrote the installation instruction.
https://github.com/UuuNyaa/blender_mmd_uuunyaa_tools/wiki#optional-winrar-or-unrar
