### ISSUE TITLE
Blender 3.4.1 didnt support this addon?

### ISSUE THREAD

**Issue by Fina07** [UuuNyaa/blender_mmd_uuunyaa_tools#95]
Traceback (most recent call last):
  File "MY PATH\Blender 3.4\3.4\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mmd_uuunyaa_tools\__init__.py", line 60, in <module>
    auto_load.init()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mmd_uuunyaa_tools\auto_load.py", line 25, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mmd_uuunyaa_tools\auto_load.py", line 53, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mmd_uuunyaa_tools\auto_load.py", line 57, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "MY PATH\Blender 3.4\3.4\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mmd_uuunyaa_tools\converters\physics\cloth.py", line 15, in <module>
    mmd_tools = import_mmd_tools()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mmd_uuunyaa_tools\utilities.py", line 72, in import_mmd_tools
    return importlib.import_module('mmd_tools')
  File "MY PATH\Blender 3.4\3.4\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmd_tools'

Does this addon support latest blender version?

**Comment by Fina07** [comment]
Ahh, I found a solution.
I need to install other mmd addons.
